<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iced" Version="1.21.0" />
    <PackageReference Include="Tomlyn" Version="0.17.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OgXbox.Recomp.Codegen.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\runtime\ogxbox_runtime.h" Link="ogxbox_runtime.h" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\runtime\ogxbox_runtime.c" Link="ogxbox_runtime.c" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\runtime\ogxbox_kernel.c" Link="ogxbox_kernel.c" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\runtime\ogxbox_main.c" Link="ogxbox_main.c" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
