// CodegenWriter — emit every sealed function to partitioned .c files + a header.
//
// Lean port of rex::codegen::CodegenWriter (ReXGlue SDK, BSD-3-Clause).

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using OgXbox.Recomp.Codegen.Phases;

namespace OgXbox.Recomp.Codegen.Emit;

public sealed class CodegenStats
{
    public int Functions;
    public int Instructions;
    public int Unimplemented;
    public readonly Dictionary<string, int> UnimplementedByMnemonic = new();
}

public static class CodegenWriter
{
    public static CodegenStats WriteAll(CodegenContext ctx, string outDir,
                                        Binary.Xbe? image = null, int functionsPerFile = 500)
    {
        Directory.CreateDirectory(outDir);
        var stats = new CodegenStats();

        if (image is not null)
            ImageWriter.Write(image, outDir);

        var emitter = new CEmitter(ctx.Decoded, a => ctx.Graph.GetFunction(a)?.Name);
        var funcs = ctx.Graph.SealedFunctions
            .Where(n => !n.IsImport && n.Blocks.Count > 0)
            .OrderBy(n => n.Base)
            .ToList();

        WriteRuntimeHeader(outDir);

        var decls = new StringBuilder();
        decls.AppendLine("/* generated — function declarations */");
        decls.AppendLine("#pragma once");
        decls.AppendLine("#include \"ogxbox_runtime.h\"");

        int fileIdx = 0;
        for (int i = 0; i < funcs.Count; i += functionsPerFile, fileIdx++)
        {
            var slice = funcs.Skip(i).Take(functionsPerFile).ToList();
            var sb = new StringBuilder();
            sb.AppendLine("/* generated by ogxbox */");
            sb.AppendLine("#include \"recomp_decls.h\"");
            sb.AppendLine();

            foreach (var fn in slice)
            {
                var r = emitter.Emit(fn);
                stats.Functions++;
                stats.Instructions += r.Instructions;
                stats.Unimplemented += r.Unimplemented;
                foreach (var m in r.UnimplementedMnemonics)
                    stats.UnimplementedByMnemonic[m] = stats.UnimplementedByMnemonic.GetValueOrDefault(m) + 1;

                decls.Append("void ").Append(fn.Name).Append("(RecompCtx* c);\n");
                sb.Append(r.Code).Append('\n');
            }

            File.WriteAllText(Path.Combine(outDir, $"recomp_{fileIdx:D4}.c"), sb.ToString());
        }

        File.WriteAllText(Path.Combine(outDir, "recomp_decls.h"), decls.ToString());
        WriteDispatchTable(ctx, outDir, funcs);
        WriteImportStubs(ctx, outDir);
        WriteCMake(outDir, fileIdx);
        return stats;
    }

    private static void WriteCMake(string outDir, int cFileCount)
    {
        var sb = new StringBuilder();
        sb.AppendLine("cmake_minimum_required(VERSION 3.16)");
        sb.AppendLine("project(recomp C)");
        sb.AppendLine("set(CMAKE_C_STANDARD 11)");
        sb.AppendLine("add_executable(recomp");
        sb.AppendLine("  ogxbox_main.c ogxbox_runtime.c ogxbox_kernel.c");
        sb.AppendLine("  recomp_dispatch.c recomp_imports.c recomp_image.c");
        for (int i = 0; i < cFileCount; i++)
            sb.AppendLine($"  recomp_{i:D4}.c");
        sb.AppendLine(")");
        sb.AppendLine("# recomp_image.bin must sit next to the executable at run time.");
        File.WriteAllText(Path.Combine(outDir, "CMakeLists.txt"), sb.ToString());
    }

    private static void WriteDispatchTable(CodegenContext ctx, string outDir,
                                           List<FunctionNode> funcs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* generated — guest address -> function, sorted for binary search */");
        sb.AppendLine("#include \"recomp_decls.h\"");
        sb.AppendLine("typedef struct { unsigned int addr; void (*fn)(RecompCtx*); } RexDispatchEntry;");
        sb.AppendLine("const RexDispatchEntry g_rex_dispatch[] = {");
        foreach (var fn in funcs.OrderBy(f => f.Base))
            sb.Append("  { 0x").Append(fn.Base.ToString("X8")).Append("u, ").Append(fn.Name).AppendLine(" },");
        sb.AppendLine("};");
        sb.Append("const unsigned int g_rex_dispatch_count = ")
          .Append(funcs.Count).AppendLine(";");
        File.WriteAllText(Path.Combine(outDir, "recomp_dispatch.c"), sb.ToString());
    }

    private static void WriteImportStubs(CodegenContext ctx, string outDir)
    {
        var imports = ctx.Graph.Functions.Values
            .Where(n => n.IsImport)
            .Select(n => n.Name)
            .Distinct()
            .OrderBy(s => s)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("/* generated — weak kernel-import stubs; a port overrides these */");
        sb.AppendLine("#include \"ogxbox_runtime.h\"");
        foreach (var name in imports)
        {
            sb.Append("#if defined(__GNUC__) || defined(__clang__)\n__attribute__((weak))\n#endif\n");
            sb.Append("void ").Append(name).Append("(RecompCtx* c) { (void)c; rex_unimplemented(\"")
              .Append(name).AppendLine("\", 0); }");
        }
        File.WriteAllText(Path.Combine(outDir, "recomp_imports.c"), sb.ToString());

        // declare them in the shared header too
        var d = Path.Combine(outDir, "recomp_decls.h");
        File.AppendAllText(d, "\n/* imports */\n" +
            string.Join("\n", imports.Select(n => $"void {n}(RecompCtx* c);")) + "\n");
    }

    private static void WriteRuntimeHeader(string outDir)
    {
        // The header ships as an embedded resource OR sits next to the assembly.
        var asmDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!;
        foreach (var name in new[]
                 {
                     "ogxbox_runtime.h", "ogxbox_runtime.c",
                     "ogxbox_kernel.c", "ogxbox_main.c",
                 })
        {
            string? src = new[]
            {
                Path.Combine(asmDir, name),
                Path.Combine(asmDir, "..", "..", "..", "..", "..", "runtime", name),
            }.FirstOrDefault(File.Exists);

            if (src is not null)
                File.Copy(src, Path.Combine(outDir, name), overwrite: true);
            else if (name.EndsWith(".h"))
                File.WriteAllText(Path.Combine(outDir, name),
                    "#error copy runtime/ogxbox_runtime.h from the SDK next to this file\n");
        }
    }
}
