// CodegenWriter — emit every sealed function to partitioned .c files + a header.
//
// Lean port of rex::codegen::CodegenWriter (ReXGlue SDK, BSD-3-Clause).

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using OgXbox.Recomp.Codegen.Phases;

namespace OgXbox.Recomp.Codegen.Emit;

public sealed class CodegenStats
{
    public int Functions;
    public int Instructions;
    public int Unimplemented;
    public readonly Dictionary<string, int> UnimplementedByMnemonic = new();
}

public static class CodegenWriter
{
    public static CodegenStats WriteAll(CodegenContext ctx, string outDir, int functionsPerFile = 500)
    {
        Directory.CreateDirectory(outDir);
        var stats = new CodegenStats();

        var emitter = new CEmitter(ctx.Decoded, a => ctx.Graph.GetFunction(a)?.Name);
        var funcs = ctx.Graph.SealedFunctions
            .Where(n => !n.IsImport && n.Blocks.Count > 0)
            .OrderBy(n => n.Base)
            .ToList();

        WriteRuntimeHeader(outDir);

        var decls = new StringBuilder();
        decls.AppendLine("/* generated — function declarations */");
        decls.AppendLine("#pragma once");
        decls.AppendLine("#include \"ogxbox_runtime.h\"");

        int fileIdx = 0;
        for (int i = 0; i < funcs.Count; i += functionsPerFile, fileIdx++)
        {
            var slice = funcs.Skip(i).Take(functionsPerFile).ToList();
            var sb = new StringBuilder();
            sb.AppendLine("/* generated by ogxbox */");
            sb.AppendLine("#include \"recomp_decls.h\"");
            sb.AppendLine();

            foreach (var fn in slice)
            {
                var r = emitter.Emit(fn);
                stats.Functions++;
                stats.Instructions += r.Instructions;
                stats.Unimplemented += r.Unimplemented;
                foreach (var m in r.UnimplementedMnemonics)
                    stats.UnimplementedByMnemonic[m] = stats.UnimplementedByMnemonic.GetValueOrDefault(m) + 1;

                decls.Append("void ").Append(fn.Name).Append("(RecompCtx* c);\n");
                sb.Append(r.Code).Append('\n');
            }

            File.WriteAllText(Path.Combine(outDir, $"recomp_{fileIdx:D4}.c"), sb.ToString());
        }

        File.WriteAllText(Path.Combine(outDir, "recomp_decls.h"), decls.ToString());
        return stats;
    }

    private static void WriteRuntimeHeader(string outDir)
    {
        // The header ships as an embedded resource OR sits next to the assembly.
        var asmDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!;
        foreach (var candidate in new[]
                 {
                     Path.Combine(asmDir, "ogxbox_runtime.h"),
                     Path.Combine(asmDir, "..", "..", "..", "..", "..", "runtime", "ogxbox_runtime.h"),
                 })
        {
            if (File.Exists(candidate))
            {
                File.Copy(candidate, Path.Combine(outDir, "ogxbox_runtime.h"), overwrite: true);
                return;
            }
        }
        // Not found — leave a stub note so the build error is obvious.
        File.WriteAllText(Path.Combine(outDir, "ogxbox_runtime.h"),
            "#error copy runtime/ogxbox_runtime.h from the SDK next to this file\n");
    }
}
